# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='users',
        ),
        migrations.AddField(
            model_name='colormarker',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='color_marker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ColorMarker'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
