# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170812_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(default=True),
        ),
    ]
