# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
