# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20170820_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_from',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_to',
            field=models.TimeField(blank=True),
        ),
    ]
