# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20170823_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='problem',
            field=models.TextField(blank=True),
        ),
    ]
