# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_colormarker_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
