# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20170901_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
