# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 16:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20170901_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 8, 16, 8, 38, 300757, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
