# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-30 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormarker',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
