# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-02 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_colormarker_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
